[package]
name = "hash"
version = "0.1.0"
authors = ["AtsushiMiyazaki <miyazaki@eversystem.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.8.2"
bs58 = "0.2.4"
