[package]
name = "rust-iost"
version = "0.1.0"
authors = ["AtsushiMiyazaki <miyazaki@eversystem.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.2.4"
ed25519-dalek = "1.0.0-pre.2"
bytes = "0.4.12"